[phases.build]
cmds = [
  "pip install -r requirements.txt",
  "python manage.py collectstatic --noinput"
]

[phases.deploy]
cmds = ["python manage.py migrate --noinput"]

[start]
cmd = "gunicorn bakery_erp.wsgi --workers 2 --timeout 120 --log-file -"
