# Generated by Django 6.0.4 on 2026-05-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TelegramSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bot_token",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Bot Token"
                    ),
                ),
                (
                    "chat_id",
                    models.CharField(blank=True, max_length=50, verbose_name="Chat ID"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Faol")),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Telegram Sozlamalari",
            },
        ),
    ]
