# Generated by Django 6.0.4 on 2026-05-21 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branches", "0001_initial"),
        ("core", "0002_telegramsettings"),
    ]

    operations = [
        migrations.CreateModel(
            name="BranchTelegramSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bot_token",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Bot Token"
                    ),
                ),
                (
                    "chat_id",
                    models.CharField(blank=True, max_length=50, verbose_name="Chat ID"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Faol")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telegram_settings",
                        to="branches.branch",
                        verbose_name="Filial",
                    ),
                ),
            ],
            options={
                "verbose_name": "Filial Telegram Sozlamalari",
            },
        ),
    ]
