# Generated by Django 6.0.4 on 2026-05-22 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_branchtelegramsettings"),
        ("hr", "0003_employee_branch"),
    ]

    operations = [
        migrations.CreateModel(
            name="CameraDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Kamera nomi")),
                ("camera_id", models.IntegerField(default=0, verbose_name="Kamera ID")),
                ("is_active", models.BooleanField(default=True, verbose_name="Faol")),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="Asosiy kamera"),
                ),
                (
                    "last_used",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Oxirgi ishlatilgan"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Kamera Qurilmasi",
                "verbose_name_plural": "Kamera Qurilmalari",
            },
        ),
        migrations.AddField(
            model_name="branchtelegramsettings",
            name="is_persistent",
            field=models.BooleanField(default=True, verbose_name="Doimiy ulanish"),
        ),
        migrations.AddField(
            model_name="telegramsettings",
            name="is_persistent",
            field=models.BooleanField(default=True, verbose_name="Doimiy ulanish"),
        ),
        migrations.CreateModel(
            name="FaceIDSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_running",
                    models.BooleanField(default=False, verbose_name="Ishlayapti"),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Boshlangan vaqt"
                    ),
                ),
                (
                    "stopped_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="To'xtatilgan vaqt"
                    ),
                ),
                (
                    "total_check_ins",
                    models.IntegerField(default=0, verbose_name="Jami kirishlar"),
                ),
                (
                    "total_check_outs",
                    models.IntegerField(default=0, verbose_name="Jami chiqishlar"),
                ),
                (
                    "camera",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.cameradevice",
                        verbose_name="Kamera",
                    ),
                ),
                (
                    "last_employee_seen",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hr.employee",
                        verbose_name="Oxirgi ko'rilgan xodim",
                    ),
                ),
            ],
            options={
                "verbose_name": "Face ID Sessiya",
                "verbose_name_plural": "Face ID Sessiyalar",
            },
        ),
    ]
