# Generated by Django 6.0.4 on 2026-05-17 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="products/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="RawMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "unit",
                    models.CharField(help_text="e.g., kg, liter, piece", max_length=50),
                ),
                (
                    "stock",
                    models.DecimalField(decimal_places=3, default=0, max_digits=10),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FinishedGoodsInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stock", models.IntegerField(default=0)),
                ("produced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory",
                        to="production.product",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="production.productcategory",
            ),
        ),
        migrations.CreateModel(
            name="ProductionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("quantity", models.IntegerField()),
                (
                    "batches",
                    models.IntegerField(
                        default=1, help_text="Number of recipe batches"
                    ),
                ),
                ("baker_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "timer_minutes",
                    models.IntegerField(
                        default=0, help_text="Production timer in minutes"
                    ),
                ),
                ("timer_started_at", models.DateTimeField(blank=True, null=True)),
                ("is_done", models.BooleanField(default=False)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="production.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch_size",
                    models.IntegerField(help_text="Quantity produced by this recipe"),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipe",
                        to="production.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RecipeItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Amount in raw_material's unit",
                        max_digits=10,
                    ),
                ),
                (
                    "quantity_grams",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Optional gram equivalent if unit is kg",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "raw_material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="production.rawmaterial",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="production.recipe",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductDayBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("balance_date", models.DateField(db_index=True)),
                (
                    "opening_qty",
                    models.IntegerField(
                        default=0,
                        help_text="Kun boshidagi qoldiq (oldingi kun closing yoki carried-forward)",
                    ),
                ),
                (
                    "closing_qty",
                    models.IntegerField(
                        blank=True, help_text="Kun yakunidagi fizik qoldiq", null=True
                    ),
                ),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="day_balances",
                        to="production.product",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("balance_date", "product"),
                        name="uniq_product_day_balance",
                    )
                ],
            },
        ),
    ]
