# Generated by Django 6.0.4 on 2026-05-17 02:43

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Shift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., 1-smena, 2-smena", max_length=100, unique=True
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
            ],
        ),
        migrations.AddField(
            model_name="attendance",
            name="check_in_method",
            field=models.CharField(
                choices=[
                    ("face_id", "Face ID"),
                    ("manual", "Qo'lda"),
                    ("card", "Karta"),
                ],
                default="manual",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="check_out_method",
            field=models.CharField(
                choices=[
                    ("face_id", "Face ID"),
                    ("manual", "Qo'lda"),
                    ("card", "Karta"),
                ],
                default="manual",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="expected_check_in",
            field=models.TimeField(
                blank=True, help_text="Kutilgan kirish vaqti", null=True
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="face_id_snapshot",
            field=models.ImageField(
                blank=True,
                help_text="Face ID tasviri",
                null=True,
                upload_to="face_id_snapshots/",
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="late_minutes",
            field=models.IntegerField(default=0, help_text="Kechikish (daqiqalar)"),
        ),
        migrations.AddField(
            model_name="employee",
            name="daily_target",
            field=models.IntegerField(
                default=0, help_text="Daily production target (nagruzka)"
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="face_id_confidence",
            field=models.DecimalField(
                decimal_places=2,
                default=85.0,
                help_text="Face ID tanishish ishonchliligi (%)",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="face_id_enrolled",
            field=models.BooleanField(
                default=False, help_text="Face ID tizimiga ulangan"
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="employees/"),
        ),
        migrations.AddField(
            model_name="employee",
            name="user_account",
            field=models.OneToOneField(
                blank=True,
                help_text="Sotuv panelidagi foydalanuvchi bilan bog'lash (ishbay avtomatik yozuvlari uchun)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employee_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="base_salary",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="employee",
            name="is_piecework",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="employee",
            name="piecework_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Rate per unit produced",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="position",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="month",
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name="EmployeePhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("photo", models.ImageField(upload_to="employee_photos/")),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False, help_text="Asosiy rasm Face ID uchun"
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="hr.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FaceIDLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("check_in", "Kirish"),
                            ("check_out", "Chiqish"),
                            ("failed", "Noto'g'ri tanish"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "confidence",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Tanishish ishonchliligi",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "snapshot",
                    models.ImageField(blank=True, null=True, upload_to="face_logs/"),
                ),
                ("is_late", models.BooleanField(default=False)),
                ("late_minutes", models.IntegerField(default=0)),
                (
                    "shift_start_time",
                    models.TimeField(
                        blank=True, help_text="Smena boshlanish vaqti", null=True
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="face_logs",
                        to="hr.employee",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="employee",
            name="shift",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employees",
                to="hr.shift",
            ),
        ),
        migrations.CreateModel(
            name="DailyReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("check_in", models.TimeField(blank=True, null=True)),
                ("check_out", models.TimeField(blank=True, null=True)),
                (
                    "units_produced",
                    models.IntegerField(
                        default=0,
                        help_text="Qo'lda kiritilgan nagruzka / ishlab chiqarish",
                    ),
                ),
                (
                    "units_from_sales",
                    models.IntegerField(
                        default=0,
                        help_text="Sotuvdan avtomatik yozilgan donalar (bog'langan sotuvchi hisobi bilan)",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "hours_expected",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("8"), max_digits=5
                    ),
                ),
                (
                    "hours_present",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "hours_absent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Kelmagan vaqt",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "hours_left_early",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Erta ketgan vaqt",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "was_present",
                    models.BooleanField(
                        default=True, help_text="False bo'lsa — kelmagan kun"
                    ),
                ),
                (
                    "absence_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "—"),
                            ("sick", "Kasal"),
                            ("personal", "Shaxsiy masala"),
                            ("approved", "Sababli (tasdiqlangan)"),
                            ("no_reason", "Sababsiz"),
                        ],
                        default="",
                        help_text="Kelmagan sababi",
                        max_length=20,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_reports",
                        to="hr.employee",
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hr.shift",
                    ),
                ),
            ],
            options={
                "unique_together": {("employee", "date", "shift")},
            },
        ),
    ]
