# Generated by Django 6.0.4 on 2026-05-19 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branches", "0001_initial"),
        ("hr", "0002_position_shift_attendance_check_in_method_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                help_text="Filial rahbari uchun - faqat o'z filialiga ruxsat",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employees",
                to="branches.branch",
            ),
        ),
    ]
